<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RazorLangVersion>Latest</RazorLangVersion>
    <UserSecretsId>7a2fce99-6f23-4719-a669-fa1586dd5b67</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
  </ItemGroup>

</Project>
