// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoutBoxApi.Data;

#nullable disable

namespace ScoutBoxApi.Migrations
{
    [DbContext(typeof(ScoutBoxDbContext))]
    [Migration("20260406084017_AddUniqueTentNameIndex")]
    partial class AddUniqueTentNameIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TargetEntityId");

                    b.HasIndex("TargetEntityType");

                    b.HasIndex("Action", "OccurredAt");

                    b.HasIndex("ActorUserId", "OccurredAt");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsUsed");

                    b.HasIndex("UsedByUserId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartKindId")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PartKindId");

                    b.HasIndex("TentId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Parts", t =>
                        {
                            t.HasCheckConstraint("CK_Parts_State_Valid", "State BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.PartKind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStandard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PartKinds", t =>
                        {
                            t.HasCheckConstraint("CK_PartKinds_DisplayOrder_Max", "DisplayOrder <= 999");

                            t.HasCheckConstraint("CK_PartKinds_DisplayOrder_Positive", "DisplayOrder > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            CreatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsStandard = true,
                            Name = "toit",
                            UpdatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            CreatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsStandard = true,
                            Name = "double toit",
                            UpdatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            CreatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsStandard = true,
                            Name = "fetiere",
                            UpdatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000104"),
                            CreatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsStandard = true,
                            Name = "piquets",
                            UpdatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000105"),
                            CreatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsStandard = true,
                            Name = "tapis de sol",
                            UpdatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000106"),
                            CreatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsStandard = true,
                            Name = "sac",
                            UpdatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000107"),
                            CreatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsStandard = true,
                            Name = "sardines",
                            UpdatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Tent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .UseCollation("NOCASE")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OverallState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TentShapeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TentShapeId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Tents", t =>
                        {
                            t.HasCheckConstraint("CK_Tents_OverallState_Valid", "OverallState BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_Tents_Size_Max", "Size <= 100");

                            t.HasCheckConstraint("CK_Tents_Size_Positive", "Size > 0");
                        });
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.TentShape", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TentShapes", t =>
                        {
                            t.HasCheckConstraint("CK_TentShapes_DisplayOrder_Max", "DisplayOrder <= 999");

                            t.HasCheckConstraint("CK_TentShapes_DisplayOrder_Positive", "DisplayOrder > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000201"),
                            CreatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tente legere a double pente.",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Canadienne",
                            UpdatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000202"),
                            CreatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tente spacieuse avec murs droits.",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Cabanon",
                            UpdatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000203"),
                            CreatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Structure conique monomat.",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Tipi",
                            UpdatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000204"),
                            CreatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Grande tente collective.",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Marabout",
                            UpdatedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.TentShapePart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartKindId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TentShapeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartKindId");

                    b.HasIndex("TentShapeId");

                    b.HasIndex("TentShapeId", "PartKindId")
                        .IsUnique();

                    b.ToTable("TentShapeParts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000301"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000101"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000201")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000302"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000102"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000201")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000303"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000103"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000201")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000304"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000104"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000201")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000305"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000105"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000201")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000306"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000106"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000201")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000307"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000107"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000201")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000308"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000101"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000202")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000309"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000102"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000202")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000310"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000103"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000202")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000311"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000104"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000202")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000312"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000105"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000202")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000313"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000106"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000202")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000314"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000107"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000202")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000315"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000101"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000203")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000316"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000102"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000203")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000317"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000103"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000203")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000318"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000104"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000203")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000319"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000105"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000203")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000320"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000106"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000203")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000321"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000107"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000203")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000322"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000101"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000204")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000323"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000102"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000204")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000324"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000103"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000204")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000325"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000104"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000204")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000326"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000105"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000204")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000327"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000106"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000204")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000328"),
                            PartKindId = new Guid("00000000-0000-0000-0000-000000000107"),
                            TentShapeId = new Guid("00000000-0000-0000-0000-000000000204")
                        });
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.AuditEvent", b =>
                {
                    b.HasOne("ScoutBoxApi.Models.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Invite", b =>
                {
                    b.HasOne("ScoutBoxApi.Models.Entities.User", "CreatedBy")
                        .WithMany("CreatedInvites")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ScoutBoxApi.Models.Entities.User", "UsedBy")
                        .WithMany("UsedInvites")
                        .HasForeignKey("UsedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("UsedBy");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Part", b =>
                {
                    b.HasOne("ScoutBoxApi.Models.Entities.User", "CreatedByUser")
                        .WithMany("CreatedParts")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.PartKind", "PartKind")
                        .WithMany("Parts")
                        .HasForeignKey("PartKindId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.Tent", "Tent")
                        .WithMany("Parts")
                        .HasForeignKey("TentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.User", "UpdatedByUser")
                        .WithMany("UpdatedParts")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("PartKind");

                    b.Navigation("Tent");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("ScoutBoxApi.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Tent", b =>
                {
                    b.HasOne("ScoutBoxApi.Models.Entities.User", "CreatedByUser")
                        .WithMany("CreatedTents")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.TentShape", "TentShape")
                        .WithMany("Tents")
                        .HasForeignKey("TentShapeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.User", "UpdatedByUser")
                        .WithMany("UpdatedTents")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("TentShape");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.TentShapePart", b =>
                {
                    b.HasOne("ScoutBoxApi.Models.Entities.PartKind", "PartKind")
                        .WithMany("TentShapeParts")
                        .HasForeignKey("PartKindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.TentShape", "TentShape")
                        .WithMany("TentShapeParts")
                        .HasForeignKey("TentShapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartKind");

                    b.Navigation("TentShape");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.PartKind", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("TentShapeParts");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Tent", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.TentShape", b =>
                {
                    b.Navigation("TentShapeParts");

                    b.Navigation("Tents");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.User", b =>
                {
                    b.Navigation("CreatedInvites");

                    b.Navigation("CreatedParts");

                    b.Navigation("CreatedTents");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UpdatedParts");

                    b.Navigation("UpdatedTents");

                    b.Navigation("UsedInvites");
                });
#pragma warning restore 612, 618
        }
    }
}
