// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoutBoxApi.Data;

#nullable disable

namespace ScoutBoxApi.Migrations
{
    [DbContext(typeof(ScoutBoxDbContext))]
    [Migration("20260625201437_ReplaceHasDataWithRuntimeSeeder")]
    partial class ReplaceHasDataWithRuntimeSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TargetEntityId");

                    b.HasIndex("TargetEntityType");

                    b.HasIndex("Action", "OccurredAt");

                    b.HasIndex("ActorUserId", "OccurredAt");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsUsed");

                    b.HasIndex("UsedByUserId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartKindId")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PartKindId");

                    b.HasIndex("TentId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("TentId", "PartKindId")
                        .IsUnique();

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.PartKind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PartKinds");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.SeedInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeeded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SeededAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SeedInfos");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Tent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("OverallState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TentModelId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TentModelId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Tents");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.TentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TentModels");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.TentModelComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStandard")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PartKindId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TentModelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartKindId");

                    b.HasIndex("TentModelId");

                    b.HasIndex("TentModelId", "PartKindId")
                        .IsUnique();

                    b.ToTable("TentModelComponents");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.TentTag", b =>
                {
                    b.Property<Guid>("TentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("TentId", "TagId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TagId");

                    b.ToTable("TentTags");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.AuditEvent", b =>
                {
                    b.HasOne("ScoutBoxApi.Models.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Invite", b =>
                {
                    b.HasOne("ScoutBoxApi.Models.Entities.User", "CreatedBy")
                        .WithMany("CreatedInvites")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ScoutBoxApi.Models.Entities.User", "UsedBy")
                        .WithMany("UsedInvites")
                        .HasForeignKey("UsedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("UsedBy");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Part", b =>
                {
                    b.HasOne("ScoutBoxApi.Models.Entities.User", "CreatedByUser")
                        .WithMany("CreatedParts")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.PartKind", "PartKind")
                        .WithMany("Parts")
                        .HasForeignKey("PartKindId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.Tent", "Tent")
                        .WithMany("Parts")
                        .HasForeignKey("TentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.User", "UpdatedByUser")
                        .WithMany("UpdatedParts")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("PartKind");

                    b.Navigation("Tent");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("ScoutBoxApi.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Tag", b =>
                {
                    b.HasOne("ScoutBoxApi.Models.Entities.User", "CreatedByUser")
                        .WithMany("CreatedTags")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.User", "UpdatedByUser")
                        .WithMany("UpdatedTags")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Tent", b =>
                {
                    b.HasOne("ScoutBoxApi.Models.Entities.User", "CreatedByUser")
                        .WithMany("CreatedTents")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.TentModel", "TentModel")
                        .WithMany("Tents")
                        .HasForeignKey("TentModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.User", "UpdatedByUser")
                        .WithMany("UpdatedTents")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("TentModel");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.TentModelComponent", b =>
                {
                    b.HasOne("ScoutBoxApi.Models.Entities.PartKind", "PartKind")
                        .WithMany("TentModelComponents")
                        .HasForeignKey("PartKindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.TentModel", "TentModel")
                        .WithMany("TentModelComponents")
                        .HasForeignKey("TentModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartKind");

                    b.Navigation("TentModel");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.TentTag", b =>
                {
                    b.HasOne("ScoutBoxApi.Models.Entities.User", "CreatedByUser")
                        .WithMany("CreatedTentTags")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.Tag", "Tag")
                        .WithMany("TentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutBoxApi.Models.Entities.Tent", "Tent")
                        .WithMany("TentTags")
                        .HasForeignKey("TentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Tag");

                    b.Navigation("Tent");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.PartKind", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("TentModelComponents");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Tag", b =>
                {
                    b.Navigation("TentTags");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.Tent", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("TentTags");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.TentModel", b =>
                {
                    b.Navigation("TentModelComponents");

                    b.Navigation("Tents");
                });

            modelBuilder.Entity("ScoutBoxApi.Models.Entities.User", b =>
                {
                    b.Navigation("CreatedInvites");

                    b.Navigation("CreatedParts");

                    b.Navigation("CreatedTags");

                    b.Navigation("CreatedTentTags");

                    b.Navigation("CreatedTents");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UpdatedParts");

                    b.Navigation("UpdatedTags");

                    b.Navigation("UpdatedTents");

                    b.Navigation("UsedInvites");
                });
#pragma warning restore 612, 618
        }
    }
}
