server {
    listen 80;
    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /manifest.json {
        add_header Cache-Control "no-cache";
        add_header Access-Control-Allow-Origin "*";
        default_type application/json;
    }

    location ~ \.apk$ {
        add_header Content-Disposition "attachment";
        add_header Cache-Control "public, max-age=3600";
    }
}
